<?php

namespace Soar\Demo;

use Illuminate\Support\ServiceProvider;

class DemoServiceProvider extends ServiceProvider
{
    protected $defer = true;

    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('demo', function ($app) {
            return new Demo($app['session'], $app['config']);
        });
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        $this->loadViewsFrom(__DIR__ . '/views', 'Demo'); // 视图目录指定
        $this->publishes([
            __DIR__.'/views' => base_path('resources/views/vendor/demo'),  // 发布视图目录到resources 下
            __DIR__.'/config/demo.php' => config_path('demo.php'), // 发布配置文件到 laravel 的config 下
        ]);
    }

    public function provides()
    {
        // 因为延迟加载 所以要定义 provides 函数 具体参考laravel 文档
        return ['demo'];
//        return parent::provides(); // TODO: Change the autogenerated stub
    }
}
